### PR TITLE
Add an ability to configure build scan fetch timeout

### LINKED ISSUE #282: Ability to configure build scan fetch timeout
Almost every time I am getting this error message while trying to run cache experiments: 

```
ERROR: Unable to connect to <My enterprise url> in order to fetch build scan: Message: java.net.SocketTimeoutException: timeout
```

It is probably related to the size of our project, it's really big 🥇 .
I didn't find an option to configure it

### PR DESCRIPTION
**Pull request by dsvoronin**
fixes #282

### CODE REVIEW

**Comment by dsvoronin** [comment]
@erichaagdev Github says `Merging is blocked, The base branch requires all commits to be signed`, i did sign it and force pushed ammended commit, it is not working that way? Or should check be retriggered somehow? Can you please help me with it?

**Comment by erichaagdev** [comment]
Hey, @dsvoronin! Thanks for the PR.

I do not see [your commit](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/284/commits) as being signed. You can see [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/261/commits) what it looks like when the commits are signed. 

image

You can find more about how to sign commits here: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by dsvoronin** [comment]
Done, thank you

**Comment by erichaagdev** [comment]
Great! I did a brief review of your changes and so far things look good to me.

We are still catching up from the holidays and have many PRs lined up [as you can see here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pulls). I expect we will be able to merge these changes soon.

Thanks again for your contribution!

**Pull request closed without merging**
